# Generated by Django 5.0 on 2023-12-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_job_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_model',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
