# Generated by Django 5.0 on 2023-12-21 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_jobseekerprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='media/profile_pic'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobseekerprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiterprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
