# Generated by Django 5.0 on 2023-12-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_job_model_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_model',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
